openapi: 3.0.0
info:
  title: Simple Items API (GET Only)
  version: 1.0.0
  description: A minimal API focusing only on GET /items for Dredd testing.

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /items:
    get:
      summary: Get a list of all items
      operationId: get_items
      # tags removed to address warning
      responses:
        '200':
          description: A list of items.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
              example:
                - id: 1
                  name: "Sample Item"
                  description: "A sample item description"
                  createdAt: "2023-01-01T10:00:00Z"

components:
  schemas:
    # ItemBase removed as it's merged into Item using allOf (which caused warnings)
    Item:
      type: object
      required:
        - id
        - name
        - createdAt
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Sample Item Name"
        description:
          type: string
          nullable: true
          example: "Optional item description"
        createdAt:
          type: string
          example: "2023-01-01T12:00:00Z"

# Root tags section removed to address warning
