openapi: 3.0.0
info:
  title: Simple Items API (GET Only)
  version: 1.0.0
  description: A minimal API focusing only on GET /items for Dredd testing.

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /items:
    get:
      summary: Get a list of all items
      operationId: get_items
      tags:
        - Items
      responses:
        '200':
          description: A list of items.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
              example:
                - id: 1
                  name: "Sample Item"
                  description: "A sample item description"
                  createdAt: "2023-01-01T10:00:00Z"

components:
  schemas:
    ItemBase:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          example: "Sample Item Name"
        description:
          type: string
          maxLength: 500
          nullable: true
          example: "Optional item description"

    Item:
      allOf:
        - $ref: '#/components/schemas/ItemBase'
        - type: object
          required:
            - id
            - createdAt
          properties:
            id:
              type: integer
              format: int64
              readOnly: true
              example: 1
            createdAt:
              type: string
              format: date-time
              readOnly: true
              example: "2023-01-01T12:00:00Z"

tags:
  - name: Items
    description: Operations related to items
